# Generated by Django 2.2.2 on 2019-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
