# Generated by Django 2.2.2 on 2019-06-29 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('97d3afc7-b86c-4664-a987-66925ee0c94b'), primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5e44ea4-8301-47e4-83e0-a91639e8fb00'), primary_key=True, serialize=False, unique=True),
        ),
    ]
